### ISSUE TITLE
TV Shows (any letter) causes script error

### ISSUE THREAD

**Issue by escape75** [jmarth/plugin.video.kmediatorrent#101]
Looks like a security issue, happens at least in OpenElec using 2.3.7 ...

As a workaround maybe we should be calling http and not https:
Error Type: class 'urllib2.URLError'
                                            Error Contents: urlopen error [Errno 1] _ssl.c:504: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error

<pre>
23:19:21 T:139720990390016 WARNING: [xbmcswift2] No converter provided, unicode should be used, but returning str value
23:19:21 T:139720990390016 WARNING: Previous line repeats 26 times.
23:19:21 T:139720990390016  NOTICE: [xbmcswift2] Request for "/eztv" matches rule for function "eztv_index"
23:19:21 T:139720948442880  NOTICE: Thread BackgroundLoader start, auto delete: false
23:19:24 T:139720990390016  NOTICE: Thread LanguageInvoker start, auto delete: false
23:19:24 T:139720990390016  NOTICE: -->Python Interpreter Initialized<--
23:19:25 T:139720990390016 WARNING: [xbmcswift2] No converter provided, unicode should be used, but returning str value
23:19:25 T:139720990390016 WARNING: Previous line repeats 26 times.
23:19:25 T:139720990390016  NOTICE: [xbmcswift2] Request for "/eztv/shows/A" matches rule for function "eztv_shows_by_letter"
23:19:25 T:139720990390016  NOTICE: Traceback (most recent call last):
23:19:25 T:139720990390016  NOTICE:   File "/storage/.kodi/addons/plugin.video.kmediatorrent/addon.py", line 7, in <module>
23:19:25 T:139720990390016  NOTICE:     plugin.run()
23:19:25 T:139720990390016  NOTICE:   File "/storage/.kodi/addons/plugin.video.kmediatorrent/resources/site-packages/xbmcswift2/plugin.py", line 334, in run
23:19:25 T:139720990390016  NOTICE:     items = self._dispatch(self.request.path)
23:19:25 T:139720990390016  NOTICE:   File "/storage/.kodi/addons/plugin.video.kmediatorrent/resources/site-packages/xbmcswift2/plugin.py", line 306, in _dispatch
23:19:25 T:139720990390016  NOTICE:     listitems = view_func(**items)
23:19:25 T:139720990390016  NOTICE:   File "/storage/.kodi/addons/plugin.video.kmediatorrent/resources/site-packages/kmediatorrent/caching.py", line 52, in _fn
23:19:25 T:139720990390016  NOTICE:     ret = fn(*a, **kwds)
23:19:25 T:139720990390016  NOTICE:   File "/storage/.kodi/addons/plugin.video.kmediatorrent/resources/site-packages/kmediatorrent/utils.py", line 178, in _fn
23:19:25 T:139720990390016  NOTICE:     items = list(items)
23:19:25 T:139720990390016  NOTICE:   File "/storage/.kodi/addons/plugin.video.kmediatorrent/resources/site-packages/kmediatorrent/scrapers/eztv.py", line 47, in eztv_shows_by_letter
23:19:25 T:139720990390016  NOTICE:     response = url_get("%s/showlist/" % BASE_URL, headers=HEADERS)
23:19:25 T:139720990390016  NOTICE:   File "/storage/.kodi/addons/plugin.video.kmediatorrent/resources/site-packages/kmediatorrent/utils.py", line 157, in url_get
23:19:25 T:139720990390016  NOTICE:     with closing(urllib2.urlopen(req)) as response:
23:19:25 T:139720990390016  NOTICE:   File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 126, in urlopen
23:19:25 T:139720990390016  NOTICE:   File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 400, in open
23:19:25 T:139720990390016  NOTICE:   File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 418, in _open
23:19:25 T:139720990390016  NOTICE:   File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
23:19:25 T:139720990390016  NOTICE:   File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 1215, in https_open
23:19:25 T:139720990390016  NOTICE:   File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 1177, in do_open
23:19:25 T:139720990390016  NOTICE: URLError: <urlopen error [Errno 1] _ssl.c:504: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error>
23:19:25 T:139720990390016   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'urllib2.URLError'>
                                            Error Contents: <urlopen error [Errno 1] _ssl.c:504: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error>
                                            Traceback (most recent call last):
                                              File "/storage/.kodi/addons/plugin.video.kmediatorrent/addon.py", line 7, in <module>
                                                plugin.run()
                                              File "/storage/.kodi/addons/plugin.video.kmediatorrent/resources/site-packages/xbmcswift2/plugin.py", line 334, in run
                                                items = self._dispatch(self.request.path)
                                              File "/storage/.kodi/addons/plugin.video.kmediatorrent/resources/site-packages/xbmcswift2/plugin.py", line 306, in _dispatch
                                                listitems = view_func(**items)
                                              File "/storage/.kodi/addons/plugin.video.kmediatorrent/resources/site-packages/kmediatorrent/caching.py", line 52, in _fn
                                                ret = fn(*a, **kwds)
                                              File "/storage/.kodi/addons/plugin.video.kmediatorrent/resources/site-packages/kmediatorrent/utils.py", line 178, in _fn
                                                items = list(items)
                                              File "/storage/.kodi/addons/plugin.video.kmediatorrent/resources/site-packages/kmediatorrent/scrapers/eztv.py", line 47, in eztv_shows_by_letter
                                                response = url_get("%s/showlist/" % BASE_URL, headers=HEADERS)
                                              File "/storage/.kodi/addons/plugin.video.kmediatorrent/resources/site-packages/kmediatorrent/utils.py", line 157, in url_get
                                                with closing(urllib2.urlopen(req)) as response:
                                              File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 126, in urlopen
                                              File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 400, in open
                                              File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 418, in _open
                                              File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 378, in _call_chain
                                              File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 1215, in https_open
                                              File "/home/stephan/projects/openelec-5.0/build.OpenELEC-Generic.x86_64-5.0.8/Python-2.7.3/.install_pkg/usr/lib/python2.7/urllib2.py", line 1177, in do_open
                                            URLError: <urlopen error [Errno 1] _ssl.c:504: error:14077438:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert internal error>
                                            -->End of Python script error report<--
23:19:25 T:139722414651264   ERROR: GetDirectory - Error getting plugin://plugin.video.kmediatorrent/eztv/shows/A
23:19:25 T:139722414651264   ERROR: CGUIMediaWindow::GetDirectory(plugin://plugin.video.kmediatorrent/eztv/shows/A) failed
23:19:25 T:139720990390016  NOTICE: Thread LanguageInvoker start, auto delete: false
23:19:25 T:139720990390016  NOTICE: -->Python Interpreter Initialized<--
23:19:25 T:139720990390016 WARNING: [xbmcswift2] No converter provided, unicode should be used, but returning str value
23:19:25 T:139720990390016 WARNING: Previous line repeats 26 times.
23:19:25 T:139720990390016  NOTICE: [xbmcswift2] Request for "/eztv" matches rule for function "eztv_index"
23:19:25 T:139720948442880  NOTICE: Thread BackgroundLoader start, auto delete: false
23:19:30 T:139720990390016  NOTICE: Thread LanguageInvoker start, auto delete: false
23:19:30 T:139720990390016  NOTICE: -->Python Interpreter Initialized<--
23:19:30 T:139720990390016 WARNING: [xbmcswift2] No converter provided, unicode should be used, but returning str value
23:19:30 T:139720990390016 WARNING: Previous line repeats 26 times.
</pre>

**Comment by jmarth** [comment]
did you try the new version 2.3.7? https://mega.co.nz/#!6UBTRTxR!BUfRvmd3lI_bVgwABvW1cGyiXo7WoLqORXEWbaGEJp0

**Comment by escape75** [comment]
Yes, that seems to be the same link as posted on the download page.
I downloaded it only about an hour and a half ago, just before creating the issue report.

**Comment by escape75** [comment]
Found this info:
https://gist.github.com/LordGaav/4674198

**Comment by jmarth** [comment]
2.3.7 seems to be working for me. Did you uninstall the old addon before installing the new one? Have you tried clearing your catch?

**Comment by escape75** [comment]
I have cleared the cache in kmediatorrent,
maybe I will try to see if there's any files left after I unistalled kmediatorrent 2.3.5

**Comment by escape75** [comment]
This might also relate only to openelec...

Apparently linux is affected and one possible solution is forcing:
ssl_version=ssl.PROTOCOL_SSLv3

**Comment by jmarth** [comment]
I will test in linux when I get the chance.

**Comment by escape75** [comment]
I cleared the settings folder after uninstalling kmediatorrent,
then installed the newest version and now it works.

I guess some stuff gets left over, nothing to do with kmediatorrent I think.

**Comment by jmarth** [comment]
glad you fixed the problem. Thanks for the update.

**Comment by smii** [comment]
Exactly the same Issue (returned?) again on kodi 15.2. Any advise?
