### ISSUE TITLE
Writing guide for scrapers?

### ISSUE THREAD

**Issue by ssy080** [jmarth/plugin.video.kmediatorrent#35]
Hello!

thank you for the great addon. I would like to add a scraper for an asian public tracker. The interface is very simple, no sign up required. It has magnet links that can be extracted. 

I've taken a look at the scraper codes and the code ends after making a search request. Once selection is made, does it go to magnet.py to extract magnet? 

Thank you.

**Comment by jmarth** [comment]
Do you already know how to do python scraping? If you do you just scrap the magnet link for the torrent and you will have something like this to play the torrent
'''
yield {
                'label': '%s'%TorrentName,
                "path": plugin.url_for("play", uri=TorrentMagnetLink),
                'is_playable': True,
 }
"''

**Comment by ssy080** [comment]
Thank you for the reply. I have some experience making xbmc addons, mainly learned from other addons and learning the code. 

I am sure I can get to the point of scraping the magnet. I tried looking for anything like above in the kmediatorrent scrapers (plugin.video.kmediatorrent-master\resources\site-packages\kmediatorrent\scrapers), but all the scraper code does is to create a menu for different parts of the webpage being scraped. I am assuming the play code is somewhere else. 

I am assuming the above code cannot be applied in a separate addon as it should rely on kmediatorrent. So should I write a python as a kmediatorrent scraper? 

Thank you!

**Comment by jmarth** [comment]
Can you reword this sentence, it does not make any sense to me. "So should I write a python as a kmediatorrent scraper?"

**Comment by ssy080** [comment]
Sorry. I guess that doesn't make sense.

I meant it as:

can I write a standalone python script with your play code above? I wouldnt
think this would work because it needs to somehow be associated with
kmediatorrent addon. So I was asking if I should write it like a scraper of
your addon.

Thank you!
2015. 1. 29. ¿ÀÀü 10:29¿¡ "jmarth" <notifications@github.com>´ÔÀÌ ÀÛ¼º:

**Comment by jmarth** [comment]
Right the scrappers in the addon are for xbmc and kmediatorrent. The "play" function getting called is in plugin.video.kmediatorrent\resources\site-packages\kmediatorrent\magnet.py
