### ISSUE TITLE
updates

### ISSUE THREAD

**Issue by jmarth** [jmarth/plugin.video.kmediatorrent#40]
Sorry about the lack of updates I have been busy with the holidays. If you have a bug or a idea for a feature please add it and I will try to get back with you as soon as I can.

**Comment by laszlomenyhart** [comment]
Another idea: 
- custom RSS feed support (similar to https://github.com/steeve/xbmctorrent/issues/95)

This would allow to write custom connections from other torrent sites as well, as rss feed generation/listing is supported by many of those.

**Comment by ssy080** [comment]
Thank you for the addon. A guide to writing the scrapers would be great!
