### ISSUE TITLE
Script failed in Kodi 14.0 on Windows 8.1 x64

### ISSUE THREAD

**Issue by qzem** [jmarth/plugin.video.kmediatorrent#57]
I am having this strange issues, when I run this addon I constantly get script failed errors, but the addon is working nevertheless :). So it is more the annoyance than a bug. Should I provide some logs? How anther thing last time that I use it, it didn't get the meta data about shows, like plot and fanart.

**Comment by Shadi86** [comment]
I get also script fail when I watch movie, it's happening sometime and it's annoying because the movie stops and I must restart the movie again

**Comment by ShadowMan1234** [comment]
I get same script failed the script fail pop up when watching a movie and after the movie stop to download. 
I have android box

**Comment by jmarth** [comment]
Script errors can be a lot of different things so they might be different for each of you. I would need to see a log to see what the error is.

**Comment by qzem** [comment]
00:23:50 T:4328  NOTICE: [plugin.video.kmediatorrent] GA: Tracking /
00:23:50 T:2652  NOTICE: Thread BackgroundLoader start, auto delete: false
00:23:50 T:5016   ERROR: Unable to find plugin extrafanart
00:23:50 T:5016   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://extrafanart/
00:23:51 T:3724  NOTICE: Thread LanguageInvoker start, auto delete: false
00:23:51 T:3724  NOTICE: -->Python Interpreter Initialized<--
00:23:51 T:3724 WARNING: [xbmcswift2] No converter provided, unicode should be used, but returning str value
00:23:52 T:5048 WARNING: Previous line repeats 23 times.
00:23:52 T:5048  NOTICE: Thread LanguageInvoker start, auto delete: false
00:23:52 T:3724 WARNING: [xbmcswift2] No converter provided, unicode should be used, but returning str value
00:23:52 T:5048 WARNING: Previous line repeats 2 times.
00:23:52 T:5048  NOTICE: -->Python Interpreter Initialized<--
00:23:52 T:5048 WARNING: [xbmcswift2] No converter provided, unicode should be used, but returning str value
00:23:52 T:5048 WARNING: Previous line repeats 26 times.
00:23:52 T:5048  NOTICE: [xbmcswift2] Request for "/eztv" matches rule for function "eztv_index"
00:23:52 T:3724  NOTICE: Traceback (most recent call last):
00:23:52 T:3724  NOTICE:   File "C:\Users\Rok Kuzem\AppData\Roaming\Kodi\addons\plugin.video.kmediatorrent\addon.py", line 7, in <module>
00:23:52 T:3724  NOTICE:     plugin.run()
00:23:52 T:3724  NOTICE:   File "C:\Users\Rok Kuzem\AppData\Roaming\Kodi\addons\plugin.video.kmediatorrent\resources\site-packages\xbmcswift2\plugin.py", line 334, in run
00:23:52 T:3724  NOTICE:     items = self._dispatch(self.request.path)
00:23:52 T:3724  NOTICE:   File "C:\Users\Rok Kuzem\AppData\Roaming\Kodi\addons\plugin.video.kmediatorrent\resources\site-packages\xbmcswift2\plugin.py", line 318, in _dispatch
00:23:52 T:3724  NOTICE:     raise NotFoundException, 'No matching view found for %s' % path
00:23:52 T:3724  NOTICE: NotFoundException: No matching view found for /extrafanart/
00:23:52 T:3724   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'xbmcswift2.urls.NotFoundException'>
                                            Error Contents: No matching view found for /extrafanart/
                                            Traceback (most recent call last):
                                              File "C:\Users\Rok Kuzem\AppData\Roaming\Kodi\addons\plugin.video.kmediatorrent\addon.py", line 7, in <module>
                                                plugin.run()
                                              File "C:\Users\Rok Kuzem\AppData\Roaming\Kodi\addons\plugin.video.kmediatorrent\resources\site-packages\xbmcswift2\plugin.py", line 334, in run
                                                items = self._dispatch(self.request.path)
                                              File "C:\Users\Rok Kuzem\AppData\Roaming\Kodi\addons\plugin.video.kmediatorrent\resources\site-packages\xbmcswift2\plugin.py", line 318, in _dispatch
                                                raise NotFoundException, 'No matching view found for %s' % path
                                            NotFoundException: No matching view found for /extrafanart/
                                            -->End of Python script error report<--
00:23:52 T:4624   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.kmediatorrent/extrafanart/
00:23:52 T:3452  NOTICE: Thread BackgroundLoader start, auto delete: false
00:23:52 T:2264   ERROR: Unable to find plugin extrafanart
00:23:52 T:2264   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://extrafanart/
00:23:53 T:4256  NOTICE: Thread LanguageInvoker start, auto delete: false
00:23:54 T:4256  NOTICE: -->Python Interpreter Initialized<--
00:23:54 T:4256 WARNING: [xbmcswift2] No converter provided, unicode should be used, but returning str value
00:23:54 T:4256 WARNING: Previous line repeats 26 times.
00:23:54 T:4256  NOTICE: Traceback (most recent call last):
00:23:54 T:4256  NOTICE:   File "C:\Users\Rok Kuzem\AppData\Roaming\Kodi\addons\plugin.video.kmediatorrent\addon.py", line 7, in <module>
00:23:54 T:4256  NOTICE:     plugin.run()
00:23:54 T:4256  NOTICE:   File "C:\Users\Rok Kuzem\AppData\Roaming\Kodi\addons\plugin.video.kmediatorrent\resources\site-packages\xbmcswift2\plugin.py", line 334, in run
00:23:54 T:4256  NOTICE:     items = self._dispatch(self.request.path)
00:23:54 T:4256  NOTICE:   File "C:\Users\Rok Kuzem\AppData\Roaming\Kodi\addons\plugin.video.kmediatorrent\resources\site-packages\xbmcswift2\plugin.py", line 318, in _dispatch
00:23:54 T:4256  NOTICE:     raise NotFoundException, 'No matching view found for %s' % path
00:23:54 T:4256  NOTICE: NotFoundException: No matching view found for /extrafanart/
00:23:54 T:4256   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'xbmcswift2.urls.NotFoundException'>
                                            Error Contents: No matching view found for /extrafanart/
                                            Traceback (most recent call last):
                                              File "C:\Users\Rok Kuzem\AppData\Roaming\Kodi\addons\plugin.video.kmediatorrent\addon.py", line 7, in <module>
                                                plugin.run()
                                              File "C:\Users\Rok Kuzem\AppData\Roaming\Kodi\addons\plugin.video.kmediatorrent\resources\site-packages\xbmcswift2\plugin.py", line 334, in run
                                                items = self._dispatch(self.request.path)
                                              File "C:\Users\Rok Kuzem\AppData\Roaming\Kodi\addons\plugin.video.kmediatorrent\resources\site-packages\xbmcswift2\plugin.py", line 318, in _dispatch
                                                raise NotFoundException, 'No matching view found for %s' % path
                                            NotFoundException: No matching view found for /extrafanart/
                                            -->End of Python script error report<--
00:23:54 T:2264   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.kmediatorrent/extrafanart/
00:23:55 T:2264   ERROR: Unable to find plugin extrafanart
00:23:55 T:2264   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://extrafanart/
00:23:55 T:3008  NOTICE: Thread LanguageInvoker start, auto delete: false
00:23:55 T:3008  NOTICE: -->Python Interpreter Initialized<--
00:23:55 T:3008 WARNING: [xbmcswift2] No converter provided, unicode should be used, but returning str value
00:23:56 T:3008 WARNING: Previous line repeats 26 times.
00:23:56 T:3008  NOTICE: Traceback (most recent call last):
00:23:56 T:3008  NOTICE:   File "C:\Users\Rok Kuzem\AppData\Roaming\Kodi\addons\plugin.video.kmediatorrent\addon.py", line 7, in <module>
00:23:56 T:3008  NOTICE:     plugin.run()
00:23:56 T:3008  NOTICE:   File "C:\Users\Rok Kuzem\AppData\Roaming\Kodi\addons\plugin.video.kmediatorrent\resources\site-packages\xbmcswift2\plugin.py", line 334, in run
00:23:56 T:3008  NOTICE:     items = self._dispatch(self.request.path)
00:23:56 T:3008  NOTICE:   File "C:\Users\Rok Kuzem\AppData\Roaming\Kodi\addons\plugin.video.kmediatorrent\resources\site-packages\xbmcswift2\plugin.py", line 318, in _dispatch
00:23:56 T:3008  NOTICE:     raise NotFoundException, 'No matching view found for %s' % path
00:23:56 T:3008  NOTICE: NotFoundException: No matching view found for /extrafanart/
00:23:56 T:3008   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'xbmcswift2.urls.NotFoundException'>
                                            Error Contents: No matching view found for /extrafanart/
                                            Traceback (most recent call last):
                                              File "C:\Users\Rok Kuzem\AppData\Roaming\Kodi\addons\plugin.video.kmediatorrent\addon.py", line 7, in <module>
                                                plugin.run()
                                              File "C:\Users\Rok Kuzem\AppData\Roaming\Kodi\addons\plugin.video.kmediatorrent\resources\site-packages\xbmcswift2\plugin.py", line 334, in run
                                                items = self._dispatch(self.request.path)
                                              File "C:\Users\Rok Kuzem\AppData\Roaming\Kodi\addons\plugin.video.kmediatorrent\resources\site-packages\xbmcswift2\plugin.py", line 318, in _dispatch
                                                raise NotFoundException, 'No matching view found for %s' % path
                                            NotFoundException: No matching view found for /extrafanart/
                                            -->End of Python script error report<--
00:23:56 T:2264   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.kmediatorrent/extrafanart/
00:23:58 T:1020  NOTICE: Thread LanguageInvoker start, auto delete: false
00:23:58 T:1020  NOTICE: -->Python Interpreter Initialized<--
00:23:58 T:1020 WARNING: [xbmcswift2] No converter provided, unicode should be used, but returning str value
00:23:58 T:1020 WARNING: Previous line repeats 26 times.
00:23:58 T:1020  NOTICE: [xbmcswift2] Request for "/eztv/shows/V" matches rule for function "eztv_shows_by_letter"
00:24:07 T:3272  NOTICE: Thread BackgroundLoader start, auto delete: false
00:24:09 T:4796  NOTICE: Thread LanguageInvoker start, auto delete: false
00:24:09 T:4796  NOTICE: -->Python Interpreter Initialized<--
00:24:09 T:4796 WARNING: [xbmcswift2] No converter provided, unicode should be used, but returning str value
00:24:10 T:3940 WARNING: Previous line repeats 23 times.
00:24:10 T:3940  NOTICE: Thread LanguageInvoker start, auto delete: false
00:24:10 T:156  NOTICE: Thread JobWorker start, auto delete: true
00:24:10 T:4796 WARNING: [xbmcswift2] No converter provided, unicode should be used, but returning str value
00:24:10 T:3940 WARNING: Previous line repeats 2 times.
00:24:10 T:3940  NOTICE: -->Python Interpreter Initialized<--
00:24:10 T:4796  NOTICE: Traceback (most recent call last):
00:24:10 T:4796  NOTICE:   File "C:\Users\Rok Kuzem\AppData\Roaming\Kodi\addons\plugin.video.kmediatorrent\addon.py", line 7, in <module>
00:24:10 T:4796  NOTICE:     plugin.run()
00:24:10 T:4796  NOTICE:   File "C:\Users\Rok Kuzem\AppData\Roaming\Kodi\addons\plugin.video.kmediatorrent\resources\site-packages\xbmcswift2\plugin.py", line 334, in run
00:24:10 T:4796  NOTICE:     items = self._dispatch(self.request.path)
00:24:10 T:4796  NOTICE:   File "C:\Users\Rok Kuzem\AppData\Roaming\Kodi\addons\plugin.video.kmediatorrent\resources\site-packages\xbmcswift2\plugin.py", line 318, in _dispatch
00:24:10 T:4796  NOTICE:     raise NotFoundException, 'No matching view found for %s' % path
00:24:10 T:4796  NOTICE: NotFoundException: No matching view found for /eztv/shows/490/seasonsextrafanart/
00:24:10 T:3940 WARNING: [xbmcswift2] No converter provided, unicode should be used, but returning str value
00:24:11 T:4796 WARNING: Previous line repeats 26 times.
00:24:11 T:4796   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'xbmcswift2.urls.NotFoundException'>
                                            Error Contents: No matching view found for /eztv/shows/490/seasonsextrafanart/
                                            Traceback (most recent call last):
                                              File "C:\Users\Rok Kuzem\AppData\Roaming\Kodi\addons\plugin.video.kmediatorrent\addon.py", line 7, in <module>
                                                plugin.run()
                                              File "C:\Users\Rok Kuzem\AppData\Roaming\Kodi\addons\plugin.video.kmediatorrent\resources\site-packages\xbmcswift2\plugin.py", line 334, in run
                                                items = self._dispatch(self.request.path)
                                              File "C:\Users\Rok Kuzem\AppData\Roaming\Kodi\addons\plugin.video.kmediatorrent\resources\site-packages\xbmcswift2\plugin.py", line 318, in _dispatch
                                                raise NotFoundException, 'No matching view found for %s' % path
                                            NotFoundException: No matching view found for /eztv/shows/490/seasonsextrafanart/
                                            -->End of Python script error report<--
00:24:11 T:3940  NOTICE: Traceback (most recent call last):
00:24:11 T:3940  NOTICE:   File "C:\Users\Rok Kuzem\AppData\Roaming\Kodi\addons\plugin.video.kmediatorrent\addon.py", line 7, in <module>
00:24:11 T:3940  NOTICE:     plugin.run()
00:24:11 T:3940  NOTICE:   File "C:\Users\Rok Kuzem\AppData\Roaming\Kodi\addons\plugin.video.kmediatorrent\resources\site-packages\xbmcswift2\plugin.py", line 334, in run
00:24:11 T:3940  NOTICE:     items = self._dispatch(self.request.path)
00:24:11 T:3940  NOTICE:   File "C:\Users\Rok Kuzem\AppData\Roaming\Kodi\addons\plugin.video.kmediatorrent\resources\site-packages\xbmcswift2\plugin.py", line 318, in _dispatch
00:24:11 T:3940  NOTICE:     raise NotFoundException, 'No matching view found for %s' % path
00:24:11 T:3940  NOTICE: NotFoundException: No matching view found for /eztv/shows/819/seasonsextrafanart/
00:24:11 T:3940   ERROR: EXCEPTION Thrown (PythonToCppException) : -->Python callback/script returned the following error<--
                                             - NOTE: IGNORING THIS CAN LEAD TO MEMORY LEAKS!
                                            Error Type: <class 'xbmcswift2.urls.NotFoundException'>
                                            Error Contents: No matching view found for /eztv/shows/819/seasonsextrafanart/
                                            Traceback (most recent call last):
                                              File "C:\Users\Rok Kuzem\AppData\Roaming\Kodi\addons\plugin.video.kmediatorrent\addon.py", line 7, in <module>
                                                plugin.run()
                                              File "C:\Users\Rok Kuzem\AppData\Roaming\Kodi\addons\plugin.video.kmediatorrent\resources\site-packages\xbmcswift2\plugin.py", line 334, in run
                                                items = self._dispatch(self.request.path)
                                              File "C:\Users\Rok Kuzem\AppData\Roaming\Kodi\addons\plugin.video.kmediatorrent\resources\site-packages\xbmcswift2\plugin.py", line 318, in _dispatch
                                                raise NotFoundException, 'No matching view found for %s' % path
                                            NotFoundException: No matching view found for /eztv/shows/819/seasonsextrafanart/
                                            -->End of Python script error report<--
00:24:11 T:4624   ERROR: XFILE::CDirectory::GetDirectory - Error getting plugin://plugin.video.kmediatorrent/eztv/shows/490/seasonsextrafanart/
00:24:11 T:2156  NOTICE:

**Comment by jmarth** [comment]
@qzem This might be cause by your skin. Does it work if you use the default confluence theme?

**Comment by qzem** [comment]
I found the problem. If I go in skin settings and disable Extra fanart, the problem I don't get script errors anymore. So you think this problem needs to be sorted within skin and not withn your plugin?

**Comment by jmarth** [comment]
Yeah I think its a problem with that skin.

**Comment by qzem** [comment]
Ok, thanks for chek this out, I will close this issue now.
