### ISSUE TITLE
Yify empty 

### ISSUE THREAD

**Issue by Shadi86** [jmarth/plugin.video.kmediatorrent#59]
Hi 
Think yify website have change anything because it's empty in kmediatorrent, any workaround will appreciate it.. Thnx

**Comment by Shadi86** [comment]
It's empty no movie in yify list

**Comment by freestylemaster** [comment]
Looks like Yify website is down at the moment.

**Comment by Shadi86** [comment]
I don't think so, I can access the site without a problem http://www.yify-torrent.org/latest.html

**Comment by freestylemaster** [comment]
this one is used https://yts.re

**Comment by Shadi86** [comment]
My fault, I hope it's temporary down or maybe they doing a maintenance
