### ISSUE TITLE
Nexus TV - plugin returned failure

### ISSUE THREAD

**Issue by luca992** [jmarth/plugin.video.kmediatorrent#60]
Nothing will load

This happens everytime.
00:34:51 T:18446744073599413696    INFO: CPythonInvoker(8, /storage/emulated/0/Android/data/org.xbmc.kodi/files/.kodi/addons/plugin.video.kmediatorrent/addon.py): script successfully run
00:34:51 T:18446744073578327064   DEBUG: bool XFILE::CPluginDirectory::WaitOnScriptResult(const string&, int, const string&, bool)- plugin returned failure
00:34:51 T:18446744073578327064   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.kmediatorrent/play/magnet....

Full Log file:
http://pastebin.com/B1txqmMG

**Comment by jmarth** [comment]
Are you running android 5.0+? There is currently a problem see issue #5

**Comment by luca992** [comment]
Yeah, okay. Looks like same issue. I'll close this
