### ISSUE TITLE
XBMC Library Integration not working

### ISSUE THREAD

**Issue by shali3** [jmarth/plugin.video.kmediatorrent#67]
When I hit the Install / Uninstall button in the Advanced Setting tab I get nothing.
I watched the log file and I see this:
ERROR: Unable to find plugin plugin.video.stream

I think the issue is in the settings.xml file: https://github.com/jmarth/plugin.video.kmediatorrent/blob/master/resources/settings.xml
lines 25,26,29 refer to an addon named "plugin.video.stream" I guess you need to change this

**Comment by jmarth** [comment]
Thanks! I dont know how I let that slip through.

**Comment by jmarth** [comment]
library integration fix is in 2.3.4
