### ISSUE TITLE
TV Series. Episode list not updating

### ISSUE THREAD

**Issue by pags80** [jmarth/plugin.video.kmediatorrent#69]
Hi. The episode lists do not always update each week. I can find the episodes when searching torrents manually. Any ideas?

**Comment by jmarth** [comment]
Can you go into more detail? Which episode list?

**Comment by pags80** [comment]
Yes through eztv. Chicago Fire Was one of the examples

**Comment by jmarth** [comment]
under scrappers and eztv try setting the domain to https://eztv.ch/

**Comment by pags80** [comment]
Thanks. Seems to have done the trick
