### ISSUE TITLE
EZTV show list updates

### ISSUE THREAD

**Issue by woody1981** [jmarth/plugin.video.kmediatorrent#70]
So i have been using this for a while and keep getting the same problem. EZTV will not update the shows (not episodes) as an example i have just added kmediatorrent to an android box and under B i get better call saul. this does not appear on my main HTPC even though i am using the same scraper eztv.unblocked.pw (i'm on sky so nothing works). Ive been running this on this machine since xbmctorrent went down and then i started to get the Gotham series that i couldnt get before. i have clicked to clear the cache but get no popup or conformation its done and exited / restarted but i get the same show list every time.

Any ideas? again as i'm on sky i need a reliable scraper/proxy.

**Comment by tomtomclub** [comment]
geo block 

try pure vpn

**Comment by woody1981** [comment]
It cant be a geoblock at the scraper works, i can access fine through a web browser, i can watch series through kmediatorrent fine it just doesn't update the new show list (i.e. a brand new show wont appear) however the episodes update for ongoing shows.  On my new box everything shows up sugesting it is a caching issue. But clicking clear cache doesnt do anything.

**Comment by woody1981** [comment]
Any way to clear the plugin cache? as i have said before its not a scraper issue and clicking clear cache does nothing. Where is the cache for this plugin so i can delete it manually

**Comment by woody1981** [comment]
Ok i have found the problem and fixed it but please read. 
The file it.eztv.shows holds a cached version of the EZTV shows for quick access by the plugin.
located in C:\Users\LivingroomKodi\AppData\Roaming\Kodi\userdata\addon_data\plugin.video.kmediatorrent\cache (specific to my machine) does not update and therefore does not show any new shows. 
I have deleted the file from cache and restarted Kodi, this forces the machine to rebuild the file. Because the clear cache option in settings doesn't work you have to manually clear the file in order for it to update. Would you be able to change the file so it either auto updates or re-enable to clear cache option from settings.
Thanks

**Comment by jmarth** [comment]
Thanks. I will work on a fix

**Comment by jmarth** [comment]
the cache should now clear in version 2.3.4. Can you confirm it now works for you?

**Comment by woody1981** [comment]
Seems to be working fine although on the first run (after it had auto cleared the cache) it just hung. Had to restart Kodi as it crashed the system. I had a look at the Log but couldnt see what was stopping it. Re-installed from zip again so i had a clean log file to send you and everything worked fine.

Only thing i can see is the plugin still shows as 2.3.3 in the video plugin list.

Great work
Thanks

**Comment by tomtomclub** [comment]
works fine now
