### ISSUE TITLE
Piratebay not working after address change

### ISSUE THREAD

**Issue by theboy181** [jmarth/plugin.video.kmediatorrent#74]
https://thepiratebay.se/
Not working.. maybe the plugin doesn't support https ??

**Comment by jmarth** [comment]
seems to be working fine for me. What problems are you having? can you upload a log

**Comment by tezer66** [comment]
Your internet provider is probably blocking the url. Try one of the many mirror urls from https://proxybay.info/

**Comment by tomtomclub** [comment]
and four yfy remove ro to to

**Comment by theboy181** [comment]
I was able to use this address from my main computer. Another adress is working though so I will close.
