### ISSUE TITLE
bug fix + permisson to write an article about the addon

### ISSUE THREAD

**Issue by Lironcn** [jmarth/plugin.video.kmediatorrent#77]
Hey man, I hope you don't mind I'm going to write an article about your addon :-)
Plus, there's an error when accessing movies currently, it can be easily solved by changing the YIFY source from yts.re to yts.to
See more details in my post here: http://www.iwillfolo.com/fix-xbmctorrent-stream-unable-to-connect-to-yify-torrents/

**Comment by jmarth** [comment]
np. This is fixed in the new version 2.3.4. Thanks.

**Comment by Lironcn** [comment]
cool
