### ISSUE TITLE
send magnet to kmediatorrent

### ISSUE THREAD

**Issue by Shadi86** [jmarth/plugin.video.kmediatorrent#81]
is it difficult to add a feature like the old xbmctorrent had, so we can send magnet to kmediatorrent it's would be a good feature, it's could send a magnet from the yatse app...thanks for the great addon and keeping up

**Comment by jmarth** [comment]
unfortunately I don't think I can do much on my side. I think yatse hard codes "xbmctorrent" instead of letting the user choose the addon. What you can do is change "plugin.video.kmediatorrent" to "plugin.video.xbmctorrent" in the addon xml and it should work.

**Comment by Shadi86** [comment]
Thanks bro for your answer

**Comment by kodispot** [comment]
You Can Use This Instead https://www.dropbox.com/s/9jbn13jvz56k86r/plugin.video.magnet4kmedia.zip?dl=1

**Comment by Shadi86** [comment]
Thanks will use it
