### ISSUE TITLE
Request.

### ISSUE THREAD

**Issue by theboy181** [jmarth/plugin.video.kmediatorrent#93]
I would like to be able to compile this. Any decent information on this out there?

**Comment by jmarth** [comment]
This requires xbmc/kodi. Just save the source folder as plugin.video.kmediatorrent-1.2.3 (1.2.3 being the version number) and add it to xbmc/kodi. Is this what you are asking for?

**Comment by theboy181** [comment]
Why is the bin larger than the source?

**Comment by theboy181** [comment]
I see a download link and the ability to download as a zip. Are you saying that I just have to rename the zip?

**Comment by theboy181** [comment]
Do you hve a repo so it will auto update?

**Comment by jmarth** [comment]
Are you asking how to add stuff/code and test it out or are you just asking how to add this plugin to xbmc/kodi?

**Comment by jmarth** [comment]
No currently it does not autoupdate

**Comment by theboy181** [comment]
I see the downloads. I would like to be able to compile the master as a usable plugin.

**Comment by jmarth** [comment]
If you just want to use the plugin, go to the main git page and you will see a download link, download it, and add it through xbmc/kodi

**Comment by theboy181** [comment]
I want the most current. Some of the covers and links to scrapers are not working on 2.3.5

**Comment by jmarth** [comment]
2.3.5 is the latest version @escape75  added some contributions to fix some of this issues and I will pull and update the plugin as soon as I can

**Comment by jmarth** [comment]
2.3.6 has been added and the download link has been updated
