### ISSUE TITLE
.git folder present in download version

### ISSUE THREAD

**Issue by escape75** [jmarth/plugin.video.kmediatorrent#94]
I guess not really a bug, but I've noticed a 50 MB .git folder (next to resources)
which is hidden and not required and more than doubles the downloaded size.

**Comment by jmarth** [comment]
ouch! Thanks for letting me know.

**Comment by escape75** [comment]
Another suggestion would be to make the fanart.jpg little lower resolution.
I think 1920x1080 would be ok, would go from 4000 K down to 250 K or so.

Here's a resized one, might make it better for low memory devices.
http://i.imgur.com/vqZwDhh.jpg
