### ISSUE TITLE
2.3.6

### ISSUE THREAD

**Issue by theboy181** [jmarth/plugin.video.kmediatorrent#95]
XBMCUbuntu

When I to install 2.3.6 I get error "does not have correct structure"

**Comment by jmarth** [comment]
are you using the mega download link? https://mega.co.nz/#!SAxRnAKA!-IUvPKdYEW6jK0pE5hOMty8kcxIKriCfEfLTg5kcGAA

**Comment by theboy181** [comment]
yes.. I'm re downloading, and will test on my other media PC

**Comment by jmarth** [comment]
Try deleting the old plugin and restarting xbmc/kodi and add 2.3.6

**Comment by theboy181** [comment]
Just tried on a media PC KODI that doesn't have it installed on it. wouldn't install same error message.

I'm trying to install from a zip in >system >addons> install from zip

**Comment by theboy181** [comment]
The first folder in the ZIP has the -2.3.6 in it the other uploads do not.. could that be the problem?

**Comment by jmarth** [comment]
Yes that most likely the problem. Dont know why it didnt give me any problems when I was testing it. I will make a new download link

**Comment by theboy181** [comment]
Thanks

**Comment by theboy181** [comment]
I renamed that folder, rezipped it, and it still didn't work.. Might be more to it ?

**Comment by jmarth** [comment]
can you uninstall the old add on and try this one 
https://mega.co.nz/#!eEowHZQB!nXB1ck60L8U43a8Mbi8rUPXPd-5IYu34A4hNMi8rlSA

**Comment by theboy181** [comment]
will do..

**Comment by escape75** [comment]
I think I've run into that bug in windows before, rebooting system fixed it.
I've never seen it happen in openelec though. Could be a different one though.

**Comment by jmarth** [comment]
Yeah ive come across the same thing in windows before too, tested in the download link in windows and mac and it seems to be working fine for me.

**Comment by theboy181** [comment]
Seems to be working fine now. Thank you very much.

**Comment by escape75** [comment]
Download down to 37 mb after removing that .git folder -, nice!

**Comment by jmarth** [comment]
Yup! Nice find!
