### ISSUE TITLE
Doesn't show info

### ISSUE THREAD

**Issue by alexgilseg** [jmarth/plugin.video.kmediatorrent#96]
Heya!!

I can't get the program to show info about what I want to watch as it does here: https://github.com/jmarth/plugin.video.kmediatorrent

On those images there are descriptions about what the marked file contain. Like summary from IMDB or something like that.. How do I activate that ?

**Comment by jmarth** [comment]
This is probably your theme. Different themes displays display the info differently.

**Comment by alexgilseg** [comment]
Okey. May I ask then what skin you are using in those images? Would be very helpful. Thanks for a great tool!

**Comment by jmarth** [comment]
It is bello
