### ISSUE TITLE
V2.3.6 (Android) Can't Play Anything

### ISSUE THREAD

**Issue by zachary545** [jmarth/plugin.video.kmediatorrent#99]
I can view all the menus, but when I click on a particular link it doesn't play. 

Here is the error found:
NOTICE: Arrow S03E20 HDTV x264-LOL[ettv] 23:39:57 T:18446744072524931280 WARNING: [xbmcswift2] No converter provided, unicode should be used, but returning str value 23:39:57 T:18446744072524931280 WARNING: Previous line repeats 3 times. 23:39:57 T:18446744072524931280 NOTICE: [plugin.video.kmediatorrent] Starting torrent2http... 23:39:57 T:18446744072524931280 NOTICE: ['/data/data/org.xbmc.kodi/files/plugin.video.kmediatorrent/torrent2http', '--encryption', '1', '--uri', 'http://extratorrent.cc/download/4156011/Arrow+S03E20+HDTV+x264-LOL%5Bettv%5D.torrent', '--dlrate', '0', '--bind', ':37724', '--dlpath', '.', '--ulrate', '0'] 23:40:18 T:18446744072502626944 ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.kmediatorrent/play/http%3A%2F%2Fextratorrent.cc%2Fdownload%2F4156011%2FArrow%2BS03E20%2BHDTV%2Bx264-LOL%255Bettv%255D.torrent] 23:40:19 T:18446744072515188976 NOTICE: Thread Timer start, auto delete: false 23:40:20 T:18446744072532548264 NOTICE: Thread BackgroundLoader start, auto delete: false 23:40:23 T:18446744072519053040 NOTICE: Previous line repeats 3 times. 23:40:23 T:18446744072519053040 NOTICE: Thread Timer start, auto delete: false 23:40:47 T:18446744072519398640 NOTICE: Previous line repeats 15 times. 23:40:47 T:18446744072519398640 NOTICE: Thread BackgroundLoader start, auto delete: false

This error keeps on appearing:
ERROR: Playlist Player: skipping unplayable item: 0

Not sure what it is, any help would be greatly appreciated. 

Great addon btw, keep up the good work!

**Comment by zachary545** [comment]
Figured it out, it was the sd card formatting. 

I really feel you should put your addon on the kodi forums, easier for you to get help as well as pushing out updates. 

Anyways, keep up the good work!

**Comment by jmarth** [comment]
glad you fixed the problem. I may put this on the kodi forums when I finish what im currently working on
